version: "3.3"
services:
  spark-master:
    image: harshitkgupta/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    networks:
      - spark-network
    volumes:
      - /Users/harshit.gupta/IdeaProjects/engine1:/jar
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/start-master.sh"
  spark-worker:
    image: harshitkgupta/spark:latest
    depends_on:
      - spark-master
    ports:
      - "8081:8080"
      - "4041:4040"
    networks:
      - spark-network
    volumes:
      - /Users/harshit.gupta/IdeaProjects/engine1:/jar  
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/start-worker.sh"
  client:
    image: harshitkgupta/spark:latest
    depends_on:
      - spark-master
    networks:
      - spark-network
    command: "/bin/bash"  
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
